# Generated by Django 2.0.4 on 2018-05-03 02:03

import DjangoUeditor.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=30)),
                ('nation_code_2', models.CharField(blank=True, max_length=2, null=True)),
                ('is_index', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='BatchOfTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('create_time', models.DateField(blank=True, null=True)),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='data/excel')),
                ('table_type', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batch_of_table',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=30, unique=True, verbose_name='学校名称')),
                ('id_code', models.CharField(max_length=30, unique=True, verbose_name='学校标识码')),
                ('area', models.CharField(blank=True, max_length=30, null=True, verbose_name='片区')),
                ('province', models.CharField(blank=True, max_length=30, null=True, verbose_name='所在地（省级）')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='所在地（城市）')),
                ('nation_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='行政区划编码')),
                ('is_vice_ministry', models.BooleanField(default=False, verbose_name='副部级高校')),
                ('is_211', models.BooleanField(default=False, verbose_name='211工程')),
                ('is_985', models.BooleanField(default=False, verbose_name='985工程')),
                ('is_985_platform', models.BooleanField(default=False, verbose_name='985平台')),
                ('is_double_first_class', models.BooleanField(default=False, verbose_name='双一流大学')),
                ('setup_time', models.DateField(blank=True, null=True, verbose_name='成立时间')),
                ('cancel_time', models.DateField(blank=True, null=True, verbose_name='注销时间')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='已撤销')),
                ('transfer_to', models.CharField(blank=True, max_length=30, null=True, verbose_name='合并后学校代码')),
            ],
            options={
                'db_table': 'college',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='EduClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'edu_class',
            },
        ),
        migrations.CreateModel(
            name='EduLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'edu_level',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('name_cn', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'field',
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=40, null=True)),
                ('province', models.CharField(blank=True, max_length=40, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('district', models.CharField(blank=True, max_length=40, null=True)),
                ('parent', models.CharField(blank=True, max_length=40, null=True)),
                ('lng', models.FloatField(default=0)),
                ('lat', models.FloatField(default=0)),
                ('geohash', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'nation',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('link', models.TextField(blank=True, null=True, verbose_name='链接')),
                ('keywords', models.CharField(blank=True, max_length=100, null=True, verbose_name='关键字')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='内容')),
                ('is_published', models.BooleanField(default=False, verbose_name='已发布')),
                ('is_allow_comments', models.BooleanField(default=True, verbose_name='允许评论')),
                ('is_stick_top', models.BooleanField(default=False, verbose_name='置顶')),
                ('is_bold', models.BooleanField(default=False, verbose_name='加粗')),
                ('create_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('publish_time', models.DateTimeField(blank=True, null=True)),
                ('comment_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='NewsAndCollege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_and_college', to='basic.College')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_and_college', to='basic.News')),
            ],
            options={
                'db_table': 'news_and_college',
            },
        ),
        migrations.CreateModel(
            name='NewsAndTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_and_tag', to='basic.News')),
            ],
            options={
                'db_table': 'news_and_tag',
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('reply', models.IntegerField(blank=True, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comment', to='basic.News')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'news_comment',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/images/')),
            ],
            options={
                'db_table': 'news_image',
            },
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'news_tag',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='basic.BatchOfTable')),
            ],
            options={
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='ProfessorAndCollegeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfessorAndCollegeRelation', to='basic.College')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfessorAndCollegeRelation', to='basic.Professor')),
            ],
            options={
                'db_table': 'professor_and_college',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='basic.BatchOfTable')),
            ],
            options={
                'db_table': 'ranking',
            },
        ),
        migrations.CreateModel(
            name='RankingAndCollegeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RankingAndCollegeRelation', to='basic.College')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RankingAndCollegeRelation', to='basic.Ranking')),
            ],
            options={
                'db_table': 'ranking_and_college',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('name_cn', models.CharField(max_length=255, unique=True)),
                ('create_time', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'table',
            },
        ),
        migrations.CreateModel(
            name='TypeOfTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cn', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'type_of_table',
            },
        ),
        migrations.CreateModel(
            name='YearSeasonMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(default=0)),
                ('text', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'year_season_month',
            },
        ),
        migrations.AddField(
            model_name='table',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Table', to='basic.TypeOfTable'),
        ),
        migrations.AddField(
            model_name='newsandtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_and_tag', to='basic.NewsTag'),
        ),
        migrations.AddField(
            model_name='news',
            name='college',
            field=models.ManyToManyField(through='basic.NewsAndCollege', to='basic.College', verbose_name='相关院校'),
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(through='basic.NewsAndTag', to='basic.NewsTag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='news',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='field',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fields', to='basic.Table'),
        ),
        migrations.AddField(
            model_name='college',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college', to='basic.Department', verbose_name='主管部门'),
        ),
        migrations.AddField(
            model_name='college',
            name='edu_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college', to='basic.EduClass', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='college',
            name='edu_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college', to='basic.EduLevel', verbose_name='办学层次'),
        ),
        migrations.AddField(
            model_name='batchoftable',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BatchOfTable', to='basic.YearSeasonMonth'),
        ),
        migrations.AddField(
            model_name='batchoftable',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BatchOfTable', to='basic.Table'),
        ),
    ]
