# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20171025_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchoftable',
            old_name='type',
            new_name='table_type',
        ),
    ]
