# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20171029_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorAndCollegeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfessorAndCollegeRelation', to='basic.College')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfessorAndCollegeRelation', to='basic.Ranking')),
            ],
            options={
                'db_table': 'professor_and_college',
            },
        ),
        migrations.CreateModel(
            name='RankingAndCollegeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RankingAndCollegeRelation', to='basic.College')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RankingAndCollegeRelation', to='basic.Ranking')),
            ],
            options={
                'db_table': 'ranking_and_college',
            },
        ),
        migrations.RemoveField(
            model_name='batchandcollegerelation',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='batchandcollegerelation',
            name='college',
        ),
        migrations.DeleteModel(
            name='BatchAndCollegeRelation',
        ),
    ]
